### ISSUE TITLE
Why server/app ?

### ISSUE THREAD

**Issue by atinux** [jurassicjs/nuxt-scheduler#1]
Wondering why this particular path?

Why not using server/schedulers/[name].ts?

**Comment by rohrig** [comment]
It was an instinctual decision because it fits well with how I structured Avantage. Seems tidy to me. 

<img width="295" alt="image" src="https://user-images.githubusercontent.com/45824492/221439846-7f498a3e-84bb-479a-957a-5f0df497e285.png">

But now that you mention it, I can see it may be useful to use the current path as a default and allow overriding via runtimeConfig.

I don't think I would have more than one scheduler file though. It seems to me having one place for all scheduled tasks is a good thing for keeping things simple and easy to find. I've worked on large Laravel projects that still only use the one kernel file for scheduled tasks. But that's just an opinion, if enough people want multi-file support I'm not dead set against it. Especially if they write the code to implement it 😄

**Comment by atinux** [comment]
Then I would simply use `server/plugins/scheduler.ts` for this usecase since the plugins are auto-imported automatically and then expose the util for end user :)

**Comment by rohrig** [comment]
Sounds reasonable to me. I'll implement it asap.

**Comment by rohrig** [comment]
@Atinux I can't get the auto-importing to work using ```server/plugins/useScheduler.ts```

> contents of useScheduler.ts
```js 
import { useScheduler as usePluginScheduler } from "#scheduler";
import say from "~~/server/app/services/say";
import { addUserTasks } from "~/server/app/services/tasks/userTasks";
import { addSalesTasks } from "~/server/app/services/tasks/salesTasks";

export default function useScheduler() {
  return useScheduler;
}

export function startScheduler() {
  const scheduler = usePluginScheduler();
  console.log('running startScheduler')

  //add jobs from other files
  addUserTasks();
  addSalesTasks();

  scheduler.run(() => {
    say("this should run every 5 seconds");
  }).everySeconds(5);

  // create as many jobs as you want here
}


```
> ~/server/app/services/tasks/userTasks.ts

```js
import say from "~/server/app/services/say";
// import { useScheduler } from "#scheduler";

export function addUserTasks() {
  const scheduler = useScheduler();
  scheduler.run(() => {
    say("running form userTasks.ts");
  }).everySeconds(5);
}

```
without explicitly importing useScheduler in userTasks it does not find useScheduler automatically as expected (unless I misunderstood what you meant by auto-importing). 

Other than the auto importing, everything works. 

Adding tasks for arbitrary files from any server path would work, but the file will have to be registered in the useScheduler plugin. Perhaps there is a way around this, but I don't know it.  

What am I missing? Any pointers would be appreciated 🙂

I'll create a branch, ```feature/test-auto-import```with my exact code if you want to check it out.

**Comment by rohrig** [comment]
Implemented! 🙂 See the latest version. 

Thank you @Atinux for the suggestion. It's definitely made this module better. I struggled to understand how simple your suggestion really was. I was overengineering the shit out of things late into the night. When I realized just how easy this was to implement, it made me love Nuxt even more. 🚀

**Comment by atinux** [comment]
🥰

**Comment by franklin-tina** [comment]
Nice refactoring!
