### ISSUE TITLE
startScheduler never runs

### ISSUE THREAD

**Issue by prashantpalikhe** [jurassicjs/nuxt-scheduler#3]
I may be overlooking something, but the singleton instance is created behind the [process.server flag](https://github.com/jurassicjs/nuxt-scheduler/blob/main/src/module.ts#L67) which is never true within a Nuxt module setup code. So, the scheduler never runs for me.

**Comment by prashantpalikhe** [comment]
Nuxt module is set up just once, so I guess we could just omit the `process.server` check. Module setup also always happens only on the server.

**Comment by rohrig** [comment]
@prashantpalikhe you're correct. The reason I use process.server is due to this issue: 

https://github.com/nuxt/nuxt/issues/19287

if you have a more elegant solution I'd be happy to merge it. 😃 

Otherwise, during development in the playground I just remove that check. Which, I understand is not ideal

**Comment by rohrig** [comment]
removed that server check in 0.0.13.
